In [1]:
import numpy as np

# Создаем массив 3x3 с числами от 1 до 9
arr = np.arange(1, 10).reshape(3, 3)

# Умножаем все элементы на 2
arr *= 2

# Заменяем элементы больше 10 на 0
arr[arr > 10] = 0

print(arr)

[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


In [3]:
import numpy as np

# Создаем массив из 20 случайных целых чисел от 1 до 100
arr = np.random.randint(1, 101, 20)

# Находим и выводим элементы, кратные 5
divisible_by_5 = arr[arr % 5 == 0]
print("Элементы, кратные 5:", divisible_by_5)

# Заменяем элементы кратные 5 на -1
arr[arr % 5 == 0] = -1

# Выводим обновленный массив
print("Обновленный массив:", arr)

Элементы, кратные 5: [15  5 35  5]
Обновленный массив: [16 77 99 16 77 86 -1 23 86 -1 72 51 34 -1 -1 74 76 36 56 79]


In [5]:
import numpy as np

# Создаем два массива 1x5 со случайными числами от 0 до 50
arr1 = np.random.randint(0, 51, (1, 5))
arr2 = np.random.randint(0, 51, (1, 5))

# Объединяем по строкам в массив 2x5
combined = np.vstack((arr1, arr2))

# Разделяем на два массива по 5 элементов каждый
split1 = combined[0, :]  # Первая строка (5 элементов)
split2 = combined[1, :]  # Вторая строка (5 элементов)

print("Первый исходный массив:\n", arr1)
print("Второй исходный массив:\n", arr2)
print("\nОбъединенный массив:\n", combined)
print("\nПервый разделенный массив:", split1)
print("Второй разделенный массив:", split2)

Первый исходный массив:
 [[ 8 11 41 45  0]]
Второй исходный массив:
 [[40  9 40 17 10]]

Объединенный массив:
 [[ 8 11 41 45  0]
 [40  9 40 17 10]]

Первый разделенный массив: [ 8 11 41 45  0]
Второй разделенный массив: [40  9 40 17 10]


In [7]:
import numpy as np

# Создаем массив из 50 равномерно распределенных чисел от -10 до 10
arr = np.linspace(-10, 10, 50)

# Вычисляем суммы
total_sum = np.sum(arr)
positive_sum = np.sum(arr[arr > 0])
negative_sum = np.sum(arr[arr < 0])

# Выводим результаты
print("Сумма всех элементов:", round(total_sum, 2))
print("Сумма положительных элементов:", round(positive_sum, 2))
print("Сумма отрицательных элементов:", round(negative_sum, 2))

Сумма всех элементов: 0.0
Сумма положительных элементов: 127.55
Сумма отрицательных элементов: -127.55


In [9]:
import numpy as np

# Создаем единичную матрицу 4x4
identity_matrix = np.eye(4)

# Создаем диагональную матрицу с заданными элементами
diagonal_matrix = np.diag([5, 10, 15, 20])

# Вычисляем суммы элементов
sum_identity = np.sum(identity_matrix)
sum_diagonal = np.sum(diagonal_matrix)

# Выводим результаты
print("Единичная матрица:\n", identity_matrix)
print("\nДиагональная матрица:\n", diagonal_matrix)
print("\nСумма элементов единичной матрицы:", sum_identity)
print("Сумма элементов диагональной матрицы:", sum_diagonal)
print("\nСравнение сумм:", 
      "Суммы равны" if sum_identity == sum_diagonal else "Суммы различны")

Единичная матрица:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Диагональная матрица:
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]

Сумма элементов единичной матрицы: 4.0
Сумма элементов диагональной матрицы: 50

Сравнение сумм: Суммы различны


In [11]:
import numpy as np

# Создаем две матрицы 3x3 со случайными числами от 1 до 20
matrix1 = np.random.randint(1, 21, size=(3, 3))
matrix2 = np.random.randint(1, 21, size=(3, 3))

# Вычисляем операции
sum_matrix = matrix1 + matrix2
diff_matrix = matrix1 - matrix2
prod_matrix = matrix1 * matrix2

# Выводим результаты
print("Первая матрица:\n", matrix1)
print("\nВторая матрица:\n", matrix2)
print("\nСумма матриц:\n", sum_matrix)
print("\nРазность матриц (Первая - Вторая):\n", diff_matrix)
print("\nПоэлементное произведение:\n", prod_matrix)

Первая матрица:
 [[17 20  2]
 [18  4 10]
 [20  4 15]]

Вторая матрица:
 [[ 9  3  2]
 [10 13  3]
 [ 7  7 15]]

Сумма матриц:
 [[26 23  4]
 [28 17 13]
 [27 11 30]]

Разность матриц (Первая - Вторая):
 [[ 8 17  0]
 [ 8 -9  7]
 [13 -3  0]]

Поэлементное произведение:
 [[153  60   4]
 [180  52  30]
 [140  28 225]]


In [13]:
import numpy as np

# Создаем матрицы
matrix1 = np.random.randint(1, 11, size=(2, 3))
matrix2 = np.random.randint(1, 11, size=(3, 2))

# Выполняем матричное умножение
result = matrix1 @ matrix2  # Можно также использовать np.dot(matrix1, matrix2)

# Выводим результаты
print("Первая матрица (2x3):\n", matrix1)
print("\nВторая матрица (3x2):\n", matrix2)
print("\nРезультат умножения (2x2):\n", result)

Первая матрица (2x3):
 [[2 6 5]
 [2 3 9]]

Вторая матрица (3x2):
 [[6 1]
 [3 5]
 [4 2]]

Результат умножения (2x2):
 [[50 42]
 [57 35]]


In [15]:
import numpy as np

# Создаем случайную матрицу 3x3 с целыми числами от 1 до 10
matrix = np.random.randint(1, 10, size=(3, 3))

# Вычисляем определитель
det = np.linalg.det(matrix)

print("Исходная матрица:\n", matrix)
print("\nОпределитель матрицы:", round(det, 2))

# Проверяем обратимость матрицы (с учетом погрешности вычислений)
if not np.isclose(det, 0, atol=1e-6):
    # Вычисляем обратную матрицу
    inv_matrix = np.linalg.inv(matrix)
    print("\nОбратная матрица (округлено до 3 знаков):\n", np.round(inv_matrix, 3))
else:
    print("\nМатрица вырождена, обратной не существует")

Исходная матрица:
 [[4 7 2]
 [6 8 7]
 [6 9 3]]

Определитель матрицы: 24.0

Обратная матрица (округлено до 3 знаков):
 [[-1.625 -0.125  1.375]
 [ 1.    -0.    -0.667]
 [ 0.25   0.25  -0.417]]


In [18]:
import numpy as np

# Создаем матрицу 4x4 со случайными числами от 1 до 50
matrix = np.random.randint(1, 51, size=(4, 4))

# Вычисляем транспонированную матрицу и след
transposed = matrix.T
trace = np.trace(matrix)

print("Исходная матрица:")
print(matrix)
print("\nТранспонированная матрица:")
print(transposed)
print("\nСлед матрицы:", trace)

Исходная матрица:
[[ 1 15 45 13]
 [22 38 29  3]
 [34  7 17 20]
 [37 33 47 14]]

Транспонированная матрица:
[[ 1 22 34 37]
 [15 38  7 33]
 [45 29 17 47]
 [13  3 20 14]]

След матрицы: 70


In [20]:
import numpy as np

# Создаем матрицу коэффициентов A
A = np.array([
    [2, 3, -1],
    [4, -1, 2],
    [-3, 5, 4]
])

# Создаем вектор правой части B
B = np.array([5, 6, -2])

# Решаем систему уравнений
solution = np.linalg.solve(A, B)

# Выводим результат
print("Решение системы:")
print(f"x = {solution[0]:.2f}")
print(f"y = {solution[1]:.2f}")
print(f"z = {solution[2]:.2f}")

Решение системы:
x = 1.64
y = 0.58
z = 0.01
